
name: 编译hanwckf的immortalwrt固件

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  MY_WORKSPACE: /home/runner
  REPOSITORY_URL: https://github.com/hanwckf/immortalwrt-mt798x
  REPOSITORY_CID: 
  REPOSITORY_DIR: /home/runner/immortalwrt
  FIRMWARE_DIR: /home/runner/immortalwrt/bin/targets/mediatek/mt7981

jobs:
  CompileFirmware:
    runs-on: ubuntu-20.04
    steps:
      - name: 初始化本项目仓库
        uses: actions/checkout@main

      - name: 初始化编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "==========================================================="
          echo "磁盘占用情况："
          df -hT
          echo "==========================================================="
          sudo rm -rf /etc/apt/sources.list.d/*
          echo "✅删除apt缓存"
          sudo rm -rf /usr/share/dotnet
          echo "✅删除.net环境"
          sudo rm -rf /usr/local/lib/android
          echo "✅删除android库"
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          echo "✅删除haskell"
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          echo "✅删除CodeQL"
          sudo docker image prune --all --force > /dev/null
          echo "✅清理docker镜像"
          echo "==========================================================="
          echo "磁盘占用情况："
          df -hT 
          echo "==========================================================="
          cd $MY_WORKSPACE
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

      - name: 拉取源码
        id: clone_repository
        run: |
          git clone --depth=1 $REPOSITORY_URL $REPOSITORY_DIR
          cd $REPOSITORY_DIR
          echo "REPOSITORY_CID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 更新feeds
        run: |
          cd $REPOSITORY_DIR
          ./scripts/feeds update -a

      - name: 安装feeds
        run: |
          cd $REPOSITORY_DIR
          ./scripts/feeds install -a

      - name: 加载defconfig设置
        run: |
          cd $REPOSITORY_DIR
          cp -f $GITHUB_WORKSPACE/config/immortalwrt-hanwckf.config .config
          make defconfig

      - name: 下载依赖
        id: download
        run: |
          cd $REPOSITORY_DIR
          make download -j$(nproc) V=10
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 编译固件
        id: compile
        if: ${{ !cancelled() && steps.download.outputs.status == 'success' }}
        run: |
          cd $REPOSITORY_DIR
          make -j$(nproc) V=s
          cd $FIRMWARE_DIR
          rm -rf packages
          echo "status=success" >> $GITHUB_OUTPUT
          echo "file_date=$(date +"%Y%m%d")" >> $GITHUB_OUTPUT
          echo "file_version=$(cat version.buildinfo)" >> $GITHUB_OUTPUT
          
      - name: 上传固件至GitHub Release
        if: ${{ !cancelled() && steps.compile.outputs.status == 'success' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: '[firmware][${{ steps.compile.outputs.file_date }}]适用于cmcc_rax3000m_nand版本的immortalwrt固件'
          tag_name: firmware-${{ steps.compile.outputs.file_date }}-${{ steps.compile.outputs.file_version }}
          body: |
            基于 ${{ env.REPOSITORY_URL }} 编译
            commit_id: ${{ env.REPOSITORY_CID }}
          files: ${{ env.FIRMWARE_DIR }}/*
